<section class="mt-3 card card-body">
    <h1>Gerenciar Cursos</h1>
    
    <div class="mt-2">
        <a href="/cursos/novo" class="btn btn-outline-dark">Novo Curso</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Carga Horaria</th>
                <th>Descrição</th>
                <th>Status</th>
                <th>Categoria</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                    foreach ($cursos ?? [] as $curso) 
                    {
                        $estaAtivo = 'Não ativo';
                        if ($curso[4] == 1) {
                            $estaAtivo = 'Ativo';
                        }
                        echo "
                        <tr>
                            <td class='fw-bold'>{$curso[0]}</td>
                            <td>{$curso[1]}</td>
                            <td>{$curso[2]}</td>
                            <td>{$curso[3]}</td>
                            <td>{$estaAtivo}</td>
                            <td>{$curso['nome']}</td>
                            <td>
                            <a href='/cursos/editar?id={$curso[0]}' class='btn btn-warning'>Editar</a>
                            <a href='/cursos/excluir?id={$curso[0]}' class='btn btn-danger'>Excluir</a>
                            </td>
                            </tr>
                            ";
                    }
                    ?>
        </tbody>
    </table>
    
</section>